import { Ticket, UserRole, TicketStatus, TicketPriority, DashboardSummary, Branch, Category, KnowledgeBaseArticle, InventoryItem, User } from '../types';

export const initialBranches: Branch[] = [
  { id: 1, name: 'Baş Ofis (Bakı)', code: 'HQ-BAKU', address: 'Nizami küç. 42', isActive: true, ticketCount: 14 },
  { id: 2, name: 'Gəncə Filialı', code: 'BR-GANJA', address: 'Atatürk pr. 18', isActive: true, ticketCount: 8 },
  { id: 3, name: 'Sumqayıt Filialı', code: 'BR-SUMQAYIT', address: 'Sülh küç. 5', isActive: true, ticketCount: 5 },
  { id: 4, name: 'Xaçmaz Filialı', code: 'BR-XACMAZ', address: 'H. Əliyev pr. 102', isActive: true, ticketCount: 2 },
];

export const initialCategories: Category[] = [
  { id: 1, name: 'Hardware (Aparat)', description: 'Kompüter, Printer, Monitor və digər fiziki qurğular', isActive: true, ticketCount: 15 },
  { id: 2, name: 'Software (Proqram)', description: 'Əməliyyat sistemi, 1C, Office proqramları, Brauzerlər', isActive: true, ticketCount: 9 },
  { id: 3, name: 'Network (Şəbəkə)', description: 'İnternet, VPN, Wi-Fi, Switç və Router nasazlıqları', isActive: true, ticketCount: 5 },
  { id: 4, name: 'Access / Auth (Giriş Hüquqları)', description: 'Domain hesabı, E-poçt şifrəsi, Aktivləşdirmə', isActive: true, ticketCount: 4 },
];

export const initialUsers: User[] = [
  { id: 1, fullName: 'Sistem Administratoru', email: 'admin@fixdesk.az', role: UserRole.Admin, branchId: 1, branchName: 'Baş Ofis (Bakı)', phone: '+994 50 111 22 33', isActive: true },
  { id: 2, fullName: 'Leyla Həsənova (Filial Müdiri)', email: 'leyla.h@fixdesk.az', role: UserRole.BranchManager, branchId: 2, branchName: 'Gəncə Filialı', phone: '+994 50 333 44 55', isActive: true },
  { id: 3, fullName: 'Vüsal Qasımov (Filial Əməkdaşı)', email: 'vusal.q@fixdesk.az', role: UserRole.BranchEmployee, branchId: 1, branchName: 'Baş Ofis (Bakı)', phone: '+994 50 444 55 66', isActive: true },
  { id: 4, fullName: 'Əli Məmmədov (İT Mütəxəssis)', email: 'ali.m@fixdesk.az', role: UserRole.ITSpecialist, branchId: 1, branchName: 'Baş Ofis (Bakı)', phone: '+994 50 222 33 44', isActive: true },
  { id: 5, fullName: 'Samir Kərimov (Sahə Mühəndisi)', email: 'samir.k@fixdesk.az', role: UserRole.FieldEngineer, branchId: 2, branchName: 'Gəncə Filialı', phone: '+994 50 666 77 88', isActive: true },
  { id: 6, fullName: 'Rəşad Nərimanov (Anbar Meneceri)', email: 'resad.n@fixdesk.az', role: UserRole.InventoryManager, branchId: 1, branchName: 'Baş Ofis (Bakı)', phone: '+994 50 555 66 77', isActive: true },
];

export const initialTickets: Ticket[] = [
  {
    id: 1,
    ticketCode: 'TICK-2026-0001',
    title: 'Baş kassirin kompüteri açılmır',
    description: 'Kompüter düyməsini basdıqda heç bir cərəyan gəlmir, monitora görüntü çıxmır.',
    status: TicketStatus.New,
    priority: TicketPriority.Urgent,
    categoryId: 1,
    categoryName: 'Hardware (Aparat)',
    branchId: 1,
    branchName: 'Baş Ofis (Bakı)',
    createdUserId: 3,
    createdUserName: 'Vüsal Qasımov (Kassir)',
    assignedUserId: 4,
    assignedUserName: 'Əli Məmmədov (İT İcraçı)',
    createdDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    slaDueDate: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    isSlaBreached: false,
    comments: [
      {
        id: 101,
        ticketId: 1,
        userId: 3,
        userName: 'Vüsal Qasımov',
        userRole: 'BranchEmployee',
        commentText: 'Kassa aparatına da elektrik gəlmir, zəhmət olmasa təcili baxın.',
        createdDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 2,
    ticketCode: 'TICK-2026-0002',
    title: 'Gəncə filialında şəbəkə kəsilməsi',
    description: 'Bütün filial üzrə lokal şəbəkə və voleybol şöbəsi internetə bağlana bilmir.',
    status: TicketStatus.InProgress,
    priority: TicketPriority.High,
    categoryId: 3,
    categoryName: 'Network (Şəbəkə)',
    branchId: 2,
    branchName: 'Gəncə Filialı',
    createdUserId: 2,
    createdUserName: 'Leyla Həsənova',
    assignedUserId: 4,
    assignedUserName: 'Əli Məmmədov (İT İcraçı)',
    createdDate: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    slaDueDate: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    isSlaBreached: false,
    comments: [
      {
        id: 102,
        ticketId: 2,
        userId: 4,
        userName: 'Əli Məmmədov',
        userRole: 'ITSpecialist',
        commentText: 'Provayderlə əlaqə saxlanıldı. Qovşaqda profalaktika aparılır.',
        createdDate: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 3,
    ticketCode: 'TICK-2026-0003',
    title: '1C Proqramında çap xətası (Error 404)',
    description: 'Qaimə çap edərkən 1C proqramı xəta verir və bağlanır.',
    status: TicketStatus.Resolved,
    priority: TicketPriority.Medium,
    categoryId: 2,
    categoryName: 'Software (Proqram)',
    branchId: 3,
    branchName: 'Sumqayıt Filialı',
    createdUserId: 3,
    createdUserName: 'Vüsal Qasımov',
    assignedUserId: 4,
    assignedUserName: 'Əli Məmmədov',
    createdDate: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
    slaDueDate: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    isSlaBreached: false,
    resolutionNotes: '1C proqramı yeniləndi və printer drayverləri təkrar quraşdırıldı.',
    resolvedDate: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 4,
    ticketCode: 'TICK-2026-0004',
    title: 'E-poçt şifrəsinin sıfırlanması',
    description: 'Şəxsi korporativ e-poçt şifrəmi unutmuşam, yenilənməsini xahiş edirəm.',
    status: TicketStatus.Closed,
    priority: TicketPriority.Low,
    categoryId: 4,
    categoryName: 'Access / Auth',
    branchId: 1,
    branchName: 'Baş Ofis (Bakı)',
    createdUserId: 3,
    createdUserName: 'Vüsal Qasımov',
    assignedUserId: 1,
    assignedUserName: 'Sistem Administratoru',
    createdDate: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
    slaDueDate: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    isSlaBreached: false,
    resolutionNotes: 'Yeni müvəqqəti şifrə SMS vasitəsilə göndərildi.',
  },
  {
    id: 5,
    ticketCode: 'TICK-2026-0005',
    title: 'Printer kartricinin yenilənməsi',
    description: 'Mühasibatlıq şöbəsində HP LaserJet printeri solğun çap edir.',
    status: TicketStatus.New,
    priority: TicketPriority.High,
    categoryId: 1,
    categoryName: 'Hardware (Aparat)',
    branchId: 2,
    branchName: 'Gəncə Filialı',
    createdUserId: 2,
    createdUserName: 'Leyla Həsənova',
    createdDate: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    slaDueDate: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    isSlaBreached: true,
  },
];

export const initialKnowledgeBase: KnowledgeBaseArticle[] = [
  {
    id: 1,
    title: 'Kompüter açılmadıqda ilk nə etməli?',
    content: '1. Cərəyan kabelinin rozetkaya tam oturub-oturmadığını yoxlayın.\n2. Uzadıcının (Surge protector) düyməsinin açıq olduğuna əmin olun.\n3. Monitorun qida kabelini yoxlayın.\n4. Problem davam edərsə "Hardware" kateqoriyasında Təcili Ticket açın.',
    categoryId: 1,
    categoryName: 'Hardware (Aparat)',
    authorName: 'Əli Məmmədov',
    viewCount: 142,
    createdDate: '2026-01-15T10:00:00Z',
  },
  {
    id: 2,
    title: '1C Proqramında Şəbəkə Xətası həlli',
    content: 'Əgər 1C "Server not responding" xətası verirsə:\n1. VPN bağlantınızın aktiv olduğunu yoxlayın.\n2. Ping 192.168.1.10 komandası ilə daxili serverə əlaqəni test edin.\n3. 1C proqramını bağlayıb administrator adı ilə yenidən başladın.',
    categoryId: 2,
    categoryName: 'Software (Proqram)',
    authorName: 'Sistem Administratoru',
    viewCount: 98,
    createdDate: '2026-02-01T14:30:00Z',
  },
  {
    id: 3,
    title: 'Korporativ Wi-Fi Şəbəkəsinə Qoşulma Təlimatı',
    content: 'Filiallarda FixDesk-Corp şəbəkəsinə qoşulmaq üçün domain istifadəçi adınız (ad.soyad@fixdesk.az) və Windows şifrənizdən istifadə edin. WPA2-Enterprise təhlükəsizlik protokolu tələb olunur.',
    categoryId: 3,
    categoryName: 'Network (Şəbəkə)',
    authorName: 'Əli Məmmədov',
    viewCount: 215,
    createdDate: '2026-02-10T11:20:00Z',
  },
];

export const initialInventory: InventoryItem[] = [
  { id: 1, name: 'Dell OptiPlex 7090 Desktop', modelOrSku: 'COMP-DELL-7090', quantity: 12, unit: 'Ədəd', categoryId: 1, categoryName: 'Hardware', minQuantityWarning: 5, lastUpdatedDate: '2026-03-01' },
  { id: 2, name: 'HP LaserJet Pro M404dn Printer', modelOrSku: 'PRNT-HP-M404', quantity: 3, unit: 'Ədəd', categoryId: 1, categoryName: 'Hardware', minQuantityWarning: 4, lastUpdatedDate: '2026-03-02' },
  { id: 3, name: 'Cisco Catalyst 2960 Switch 24-Port', modelOrSku: 'NET-CISCO-2960', quantity: 6, unit: 'Ədəd', categoryId: 3, categoryName: 'Network', minQuantityWarning: 2, lastUpdatedDate: '2026-02-20' },
  { id: 4, name: 'HP 05A Black Toner Cartridge', modelOrSku: 'TONER-HP-05A', quantity: 2, unit: 'Ədəd', categoryId: 1, categoryName: 'Hardware', minQuantityWarning: 10, lastUpdatedDate: '2026-03-05' },
  { id: 5, name: 'Logitech MK270 Wireless Combo', modelOrSku: 'ACC-LOGI-MK270', quantity: 25, unit: 'Dəst', categoryId: 1, categoryName: 'Hardware', minQuantityWarning: 8, lastUpdatedDate: '2026-03-04' },
];

export const mockDashboardSummary: DashboardSummary = {
  totalTickets: 29,
  openTickets: 12,
  inProgressTickets: 8,
  resolvedTickets: 7,
  slaBreachedTickets: 2,
  branchStatistics: [
    { branchId: 1, branchName: 'Baş Ofis (Bakı)', count: 14 },
    { branchId: 2, branchName: 'Gəncə Filialı', count: 8 },
    { branchId: 3, branchName: 'Sumqayıt Filialı', count: 5 },
    { branchId: 4, branchName: 'Xaçmaz Filialı', count: 2 },
  ],
  categoryStatistics: [
    { categoryId: 1, categoryName: 'Hardware', count: 15 },
    { categoryId: 2, categoryName: 'Software', count: 9 },
    { categoryId: 3, categoryName: 'Network', count: 5 },
    { categoryId: 4, categoryName: 'Access / Auth', count: 4 },
  ],
  specialistPerformances: [
    { specialistId: 4, specialistName: 'Əli Məmmədov', assignedCount: 18, resolvedCount: 14, avgResolutionTimeHours: 1.8 },
    { specialistId: 1, specialistName: 'Sistem Admin', assignedCount: 11, resolvedCount: 10, avgResolutionTimeHours: 0.9 },
  ],
};
